from .esconv import ESCONV_STRATEGIES_TO_EXPLAIN
from .extes import EXTES_STRATEGIES_TO_EXPLAIN

STRATEGIES = {
    "esconv": ESCONV_STRATEGIES_TO_EXPLAIN,
    "extes": EXTES_STRATEGIES_TO_EXPLAIN,
}
